# Generated by Django 4.1 on 2022-09-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_worker_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='age',
        ),
    ]
